// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF983ba4atzwITcHcBBnkzHjyaG5QOSdQ',
    appId: '1:307993301190:web:4414899e9d03744bee87c7',
    messagingSenderId: '307993301190',
    projectId: 'inventory-management-app-100fc',
    authDomain: 'inventory-management-app-100fc.firebaseapp.com',
    storageBucket: 'inventory-management-app-100fc.firebasestorage.app',
    measurementId: 'G-18J79L5QZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnpEHQa1monDzdjvcghr2QEfxcM1pDP0',
    appId: '1:307993301190:android:bca36592d85750edee87c7',
    messagingSenderId: '307993301190',
    projectId: 'inventory-management-app-100fc',
    storageBucket: 'inventory-management-app-100fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXQBMrJb_7tVwERO7DQHYg4u3TKcdBCU',
    appId: '1:307993301190:ios:1f17eb01e1fd8091ee87c7',
    messagingSenderId: '307993301190',
    projectId: 'inventory-management-app-100fc',
    storageBucket: 'inventory-management-app-100fc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXQBMrJb_7tVwERO7DQHYg4u3TKcdBCU',
    appId: '1:307993301190:ios:1f17eb01e1fd8091ee87c7',
    messagingSenderId: '307993301190',
    projectId: 'inventory-management-app-100fc',
    storageBucket: 'inventory-management-app-100fc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF983ba4atzwITcHcBBnkzHjyaG5QOSdQ',
    appId: '1:307993301190:web:10fd7cb07bf6de39ee87c7',
    messagingSenderId: '307993301190',
    projectId: 'inventory-management-app-100fc',
    authDomain: 'inventory-management-app-100fc.firebaseapp.com',
    storageBucket: 'inventory-management-app-100fc.firebasestorage.app',
    measurementId: 'G-W4YM0RBNRK',
  );
}
